(function(n){var m=window.AmazonUIPageJS||window.P,p=m._namespace||m.attributeErrors,q=p?p("BrandFollowButtonJS",""):m;q.guardFatal?q.guardFatal(n)(q,window):q.execute(function(){n(q,window)})})(function(n,m,p){var q="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?function(g){return typeof g}:function(g){return g&&"function"===typeof Symbol&&g.constructor===Symbol&&g!==Symbol.prototype?"symbol":typeof g},z=function(){function g(b,a){for(var e=0;e<a.length;e++){var f=a[e];f.enumerable=
f.enumerable||!1;f.configurable=!0;"value"in f&&(f.writable=!0);Object.defineProperty(b,f.key,f)}}return function(b,a,e){a&&g(b.prototype,a);e&&g(b,e);return b}}();n.when("A").register("brand-follow-constants",function(){return{PAGE_LOCALE:m.top.document.documentElement.lang,Brand_FOLLOW_BUTTON_CONTAINER_SELECTOR:"span[class*\x3dbrand-follow-button-container]",Brand_FOLLOW_BUTTON_WRAPPER_SELECTOR:"span[class*\x3dbrand-follow-button]",Brand_FOLLOW_BUTTON_SELECTOR:"button[data-bfid]",Brand_FOLLOW_BUTTON_WITH_TOOLTIP_SELECTOR:'button[data-bfid][data-showtooltip\x3d"true"]',
BRAND_FOLLOW_STATUS_MAP:"brand-follow-status",BRAND_FOLLOW_STATUS:{FOLLOWING:"following",NOT_FOLLOWING:"not_following",PENDING:"pending",NOT_SIGNED_IN:"not_signed_in",ERROR:"error"},BRAND_FOLLOW_CSRF_KEY:"brand-follow-csrf",BRAND_FOLLOW_CSRF_DATA_KEY:"csrf",BRAND_FOLLOW_LAST_CLICK_EVENT_MAP:"brand-follow-last-click-event-map",BFID_DATA_KEY:"bfid",REF_DATA_KEY:"ref",FOLLOW_STATUS_DATA_KEY:"followstatus",FOLLOW_TEXT_DATA_KEY:"followtext",FOLLOWING_TEXT_DATA_KEY:"followingtext",REQUEST_ID_DATA_KEY:"requestid",
PLACEMENT_TYPE_DATA_KEY:"placementtype",PLACEMENT_SUB_TYPE_DATA_KEY:"placementsubtype",PLACEMENT_ID_DATA_KEY:"placementid",COMPONENT_TYPE_DATA_KEY:"componenttype",COMPONENT_ID_DATA_KEY:"componentid",ELEMENT_TYPE_DATA_KEY:"elementtype",ELEMENT_ID_DATA_KEY:"elementid",TOOLTIP_TEXT_DATA_KEY:"tooltiptext",BACK_BUTTON_SUPPORT_ENABLED_DATA_KEY:"backbuttonsupportenabled",ARIA_LABEL_KEY:"aria-label",ARIA_LABEL_FOLLOW_DATA_KEY:"arialabelfollow",ARIA_LABEL_FOLLOWING_DATA_KEY:"arialabelfollowing",FOLLOWED_BRAND_TOOLTIP_SIGNAL:"followed_brand_signal",
TOOLTIP_LAST_SEEN_KEY:"tooltip_last_seen",TOOLTIP_LATEST_TEXT_KEY:"tooltip_latest_text",TOOLTIP_SEEN_COUNTER:"tooltip_seen_counter",TOOLTIP_DISPLAY_TIME:5E3,TOOLTIP_STATUS_SHOWN:"SHOWN",TOOLTIP_STATUS_NOT_SHOWN:"NOT_SHOWN",TOOLTIP_STATUS_DISABLED:"DISABLED",FOLLOW_AJAX_TIMEOUT:2E3,FOLLOW_AJAX_RETRIES:2,FOLLOW_ENDPOINT:"/followv2/follow",FOLLOW_ENTITY_TYPE:"brand",FOLLOW_REF_TAG:"bsn_as_follow",FOLLOW_CSM_PREFIX:"BrandFollow",FOLLOW_CSM_SUCCESS:"Success",FOLLOW_CSM_FAIL:"Fail",FOLLOW_CSM_FOLLOW:"Follow",
FOLLOW_CSM_UNFOLLOW:"Unfollow",FOLLOW_CSM_GET_FOLLOW_STATUS:"GetFollowStatus",HTTP_GET:"GET",HTTP_POST:"POST",HTTP_DELETE:"DELETE",SIGN_IN_PORTAL:"/ap/signin",AUTH_PORTAL_ASSOC_HANDLE:{"amazon.com":"usflex","amazon.ca":"caflex","amazon.com.mx":"mxflex","amazon.com.br":"brflex","amazon.com.co":"coflex","amazon.cl":"clflex","amazon.co.uk":"gbflex","amazon.de":"deflex","amazon.es":"esflex","amazon.fr":"frflex","amazon.in":"inflex","amazon.it":"itflex","amazon.ae":"aeflex","amazon.sa":"saflex","amazon.nl":"nlflex",
"amazon.com.be":"beflex","amazon.co.za":"zaflex","amazon.com.ng":"ngflex","amazon.co.jp":"jpflex","amazon.com.au":"auflex","amazon.sg":"sgflex"},BREAKPOINTS:{MOBILE:840},SUSHI_ENDPOINT:{gamma:"https://unagi-na.amazon.com/1/events/com.amazon.eel.BrandFollowButtonMetrics.Gamma.ClientEvents",prod:"https://unagi-na.amazon.com/1/events/com.amazon.eel.BrandFollowButtonMetrics.Prod.ClientEvents"},EVENT_TYPE:{FOLLOW:"Follow",UNFOLLOW:"Unfollow"}}});"use strict";n.when("A","brand-follow-constants").register("brand-follow-auth-portal-link-builder",
function(g,b){return{signin:function(){var a={"openid.ns":"http://specs.openid.net/auth/2.0","openid.claimed_id":"http://specs.openid.net/auth/2.0/identifier_select","openid.identity":"http://specs.openid.net/auth/2.0/identifier_select","openid.mode":"checkid_setup","openid.return_to":m.location.href,"openid.assoc_handle":b.AUTH_PORTAL_ASSOC_HANDLE[m.location.hostname.replace(/.+?(?=amazon)/,"")]};return b.SIGN_IN_PORTAL+"?"+g.$.param(a)}}});"use strict";n.register("brand-follow-csm-helper",function(){return{incrementCSMCounter:function(g,
b){m.ue&&m.ue.count&&m.ue.count(g,(m.ue.count(g)||0)+1,b)},logBodyBegin:function(g){"function"==typeof uet&&uet("bb",g,{wb:1})},sendCsmMetrics:function(g){"function"==typeof uex&&uex("ld",g,{wb:1})}}});"use strict";n.when("A","brand-follow-constants","brand-follow-csm-helper").register("brand-follow-data-storage-helper",function(g,b,a){var e={set:function(a,b,e){var h={};h[b]=e;g.state(a,h)},get:function(a){return g.state(a)},setFollowStatus:function(a,l){e.set(b.BRAND_FOLLOW_STATUS_MAP,a,l)},getFollowStatus:function(a){var l=
e.get(b.BRAND_FOLLOW_STATUS_MAP);return l===p?p:l[a]},setLastClickEvent:function(a,l){e.set(b.BRAND_FOLLOW_LAST_CLICK_EVENT_MAP,a,l)},getLastClickEvent:function(f){var l=b.FOLLOW_CSM_PREFIX+":dataStorageHelper:getLastClickAction";a.incrementCSMCounter(l);var k=e.get(b.BRAND_FOLLOW_LAST_CLICK_EVENT_MAP);if(k===p)return a.incrementCSMCounter(l+":emptyMap"),p;(f=k[f])||a.incrementCSMCounter(l+":notFoundInMap");return f},setCsrf:function(a){e.set(b.BRAND_FOLLOW_CSRF_KEY,b.BRAND_FOLLOW_CSRF_DATA_KEY,a)},
getCsrf:function(){var a=e.get(b.BRAND_FOLLOW_CSRF_KEY);return a===p?p:a[b.BRAND_FOLLOW_CSRF_DATA_KEY]}};return e});"use strict";n.when("A","brand-follow-constants","brand-follow-data-storage-helper","brand-follow-csm-helper").register("brand-follow-afs-helper",function(g,b,a,e){var f={makeCallToAfs:function(a,k,h,d,c,t){var f=b.FOLLOW_CSM_PREFIX+":"+a;e.incrementCSMCounter(f);(function A(u){e.logBodyBegin(t);g.$.ajax({url:k,type:a,headers:{Accept:"application/json","Content-Type":"application/json"},
data:h,dataType:"json",cache:!1,timeout:b.FOLLOW_AJAX_TIMEOUT,success:function(a,c,l){e.incrementCSMCounter(f+":"+b.FOLLOW_CSM_SUCCESS);e.sendCsmMetrics(t);"function"===typeof d&&d(a,c,l)},error:function(d,k,h){if("timeout"===k&&u)e.incrementCSMCounter(f+":timeout"),A(--u);else{var g=f+":"+b.FOLLOW_CSM_FAIL;e.incrementCSMCounter(g);"timeout"===k&&e.incrementCSMCounter(g+":timeout");e.sendCsmMetrics(t);m.ueLogError&&m.ueLogError({logLevel:"WARN",attribution:"BrandFollowKataComponentAssets",message:"AFS "+
a+" call failed with status "+k+", error thrown: "+h+", response text: "+d.responseText});"function"===typeof c&&c(d,k,h)}}})})(b.FOLLOW_AJAX_RETRIES)},getFollowStatusAndInitCsrf:function(e,k,h,d,c){f.makeCallToAfs(b.HTTP_GET,b.FOLLOW_ENDPOINT+"/"+e+"_"+b.FOLLOW_ENTITY_TYPE,{ref:k},function(d,b,e){d.signedIn?(a.setCsrf(d.csrf),"function"===typeof h&&h(d)):"function"===typeof c&&c()},d,b.FOLLOW_CSM_PREFIX+":"+b.FOLLOW_CSM_GET_FOLLOW_STATUS)},follow:function(e,k,h,d,c){var t=b.FOLLOW_CSM_PREFIX+":"+
b.FOLLOW_CSM_FOLLOW,g=function(){f.makeCallToAfs(b.HTTP_POST,b.FOLLOW_ENDPOINT,JSON.stringify({authenticity_token:a.getCsrf(),entity_id:e,category:b.FOLLOW_ENTITY_TYPE,ref:k}),h,d,t)};a.getCsrf()===p?f.getFollowStatusAndInitCsrf(e,k,g,p,c):g()},unfollow:function(e,k,h,d){var c=b.FOLLOW_CSM_PREFIX+":"+b.FOLLOW_CSM_UNFOLLOW,t=function(){f.makeCallToAfs(b.HTTP_DELETE,b.FOLLOW_ENDPOINT+"/"+e+"_"+b.FOLLOW_ENTITY_TYPE+"?"+g.$.param({authenticity_token:a.getCsrf(),ref:k}),p,h,d,c)};a.getCsrf()===p?f.getFollowStatusAndInitCsrf(e,
k,t):t()}};return f});"use strict";n.when("A").register("brand-follow-button-tooltip-factory",function(g){g=g.$;var b=g("\x3cdiv class\x3d'brand-follow-tooltip-root'/\x3e").appendTo("body");return{getOrCreateTooltip:function(){0===b.children().length&&b.append("\x3cdiv role\x3d'tooltip' class\x3d'bf-tooltip' id\x3d'bf-tooltip' aria-hidden\x3d'true' style\x3d'z-index: 299; display: none;'\x3e\x3cdiv class\x3d'bf-tooltip-inner'\x3eFollow to get deals, content, and email updates from this brand.\x3c/div\x3e\x3cdiv class\x3d'bf-arrow-border'\x3e\x3cdiv class\x3d'bf-arrow'\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e");
return b.children().first()}}});"use strict";n.when("A").register("brand-follow-button-tooltip-position",function(g){function b(){if(1===g.viewport().zoom)return{top:0,left:0};h||(h=k('\x3cspan id\x3d"bf-tooltip-offset-tracker"\x3e\x3c/span\x3e'),k("body").prepend(h));var a;k.withoutRtl(function(){a=h.offset()});return a}function a(a,c){var e=g.viewport(),l=b(),f,h;k.withoutRtl(function(){f=c.offset();h=a.offset()});f.top-=l.top;f.left-=l.left;h.top-=l.top;h.left-=l.left;var m=c.outerWidth(),r=c.outerHeight(),
n=a.outerWidth(!0),p=a.outerHeight(!0);return{windowWidth:e.width,windowHeight:e.height,windowTop:e.scrollTop,windowLeft:e.scrollLeft,windowRight:e.scrollLeft+e.width,windowBottom:e.scrollTop+e.height,zoomTop:l.top,zoomLeft:l.left,triggerWidth:m+1,triggerHeight:r,triggerTop:f.top-1,triggerLeft:f.left-1,triggerRight:f.left+m+1,triggerBottom:f.top+r+1,triggerVerticalCenter:f.top+r/2,triggerHorizontalCenter:f.left+m/2,popoverWidth:n,popoverHeight:p,popoverTop:h.top,popoverLeft:h.left,popoverRight:h.left+
n,popoverBottom:h.top+p,popoverVerticalCenter:h.top+p/2,popoverHorizontalCenter:h.left+n/2}}function e(a){return a.removeClass("a-arrow-top a-arrow-bottom a-arrow-left a-arrow-right")}function f(a){var c={deltaTop:0},e;c.top=a.triggerVerticalCenter-a.popoverHeight/2;c.top<a.windowTop+15?(e=Math.min(a.windowTop+15,a.triggerTop-15),c.deltaTop=c.top-e,c.top=e):c.top+a.popoverHeight>a.windowBottom-15&&(e=Math.min(15,a.windowBottom-a.triggerBottom+15),c.deltaTop=c.top+a.popoverHeight-(a.windowBottom-e),
c.top=a.windowBottom-e-a.popoverHeight);return c}function l(a){var c={deltaLeft:0},e;c.left=a.triggerHorizontalCenter-a.popoverWidth/2;15>c.left?(e=Math.min(15,a.triggerLeft-15),c.deltaLeft=c.left-e,c.left=e):c.left+a.popoverWidth>a.windowRight-15&&(e=Math.min(15,a.windowRight-a.triggerRight+15),c.deltaLeft=c.left+a.popoverWidth-(a.windowRight-e),c.left=a.windowRight-e-a.popoverWidth);return c}var k=g.$;k(m);var h=null;return{windowCenter:function(d){d=a(d.$popover,d.$trigger);var c={};c.top=(d.windowHeight-
d.popoverHeight)/2;c.left=(d.windowWidth-d.popoverWidth)/2;0>c.top&&(c.top=0);return c},windowTop:function(d){d=a(d.$popover,d.$trigger);var c={top:0};c.left=d.windowWidth/2-d.popoverWidth/2;return c},windowFullWidth:function(a){return{top:0,left:0}},triggerRight:function(d,c){var b=d.$popover;d=d.$trigger;c||(c=a(b,d));d=f(c);d.left=c.triggerRight;e(b).addClass("a-arrow-right");b.find(".bf-arrow-border").css("top",c.popoverHeight/2+d.deltaTop);return d},triggerLeft:function(d,c){var b=d.$popover;
d=d.$trigger;c||(c=a(b,d));d=f(c);d.left=c.triggerLeft-c.popoverWidth;d.left=0<d.left?d.left:0;e(b).addClass("a-arrow-left");b.find(".bf-arrow-border").css("top",c.popoverHeight/2+d.deltaTop);return d},triggerTop:function(d,c){var b=d.$popover;d=d.$trigger;c||(c=a(b,d));d=l(c);d.top=c.triggerTop-c.popoverHeight;e(b).addClass("a-arrow-top");b.find(".bf-arrow-border").css("left",c.popoverWidth/2+d.deltaLeft);return d},triggerBottom:function(d,c){var b=d.$popover;d=d.$trigger;c||(c=a(b,d));d=l(c);d.top=
c.triggerBottom;e(b).addClass("a-arrow-bottom");b.find(".bf-arrow-border").css("left",c.popoverWidth/2+d.deltaLeft);return d},triggerHorizontal:function(d,c){var e=d.$popover,b=d.$trigger;c||(c=a(e,b));return c.triggerLeft-c.windowLeft>c.windowRight-c.triggerRight?this.triggerLeft(d,c):this.triggerRight(d,c)},triggerVertical:function(d,c){var e=d.$popover,b=d.$trigger;c=c?c:a(e,b);return c.triggerTop-c.windowTop>c.popoverHeight+15?this.triggerTop(d,c):this.triggerBottom(d,c)},triggerVerticalAlignLeft:function(d,
c){var b=d.$popover;d=d.$trigger;c||(c=a(b,d));d={};var l=0,f=0,h=c.windowBottom-c.triggerBottom;d.left=c.triggerLeft;d.top=h>c.popoverHeight?c.triggerBottom+3:c.triggerTop-c.popoverHeight-3;15>d.left?(f=Math.min(15,c.triggerLeft-15),l=d.left-f,d.left=f):d.left+c.popoverWidth>c.windowRight-15&&(f=Math.min(15,c.windowRight-c.triggerRight+15),l=d.left+c.popoverWidth-(c.windowRight-f),d.left=c.windowRight-f-c.popoverWidth);e(b).addClass(h>c.popoverHeight?"a-arrow-bottom":"a-arrow-top");k.withoutRtl(function(){b.find(".bf-arrow-border").css("left",
c.triggerWidth/2+l)});return d},triggerBottomAlignRight:function(d,c){var b=d.$popover;d=d.$trigger;c||(c=a(b,d));d={};var l=0,f=0,h=c.windowBottom-c.triggerBottom;d.left=c.triggerRight-c.popoverWidth;d.top=c.triggerBottom+3;15>d.left?(f=Math.max(0,d.left),l=f-d.left,d.left=f):d.left+c.popoverWidth>c.windowRight-15&&(f=Math.min(15,c.windowRight-c.triggerRight+15),l=d.left+c.popoverWidth-(c.windowRight-f),d.left=c.windowRight-f-c.popoverWidth);e(b).addClass(h>c.popoverHeight?"a-arrow-bottom":"a-arrow-top");
k.withoutRtl(function(){b.find(".bf-arrow-border").css("right",c.triggerWidth/2+l)});return d},customPosition:function(d,c){return c.call(this,{popover:d,$popover:d.$popover,$trigger:d.$trigger,measure:a})}}});"use strict";n.when("A","brand-follow-button-tooltip-factory","brand-follow-button-tooltip-position","brand-follow-constants").register("brand-follow-button-tooltip",function(g,b,a,e){var f=g.$;return{show:function(l){var k=b.getOrCreateTooltip(),h=f(l);l=h.data(e.TOOLTIP_TEXT_DATA_KEY);h=a.triggerBottomAlignRight({$popover:k,
$trigger:h});l&&k.find(".bf-tooltip-inner").first().text(l);k.css({top:h.top+"px",left:h.left+6+"px"});k.fadeIn(500)},hide:function(){b.getOrCreateTooltip().fadeOut(500)},getText:function(){return b.getOrCreateTooltip().find(".bf-tooltip-inner").first().text()}}});"use strict";n.register("brand-follow-sushi-client",function(){var g=["messageId","timestamp"];return function(){function b(a,e){if(!(this instanceof b))throw new TypeError("Cannot call a class as a function");this.endpoint=e;this.window=
a;this.eventsQueue=[];this.eventsDictionary={};this.reverseEventsDictionary={};this.eventSequence=this.lowPriorityTimer=this.highPriorityTimer=this.rejectedEvents=this.dictionaryIndex=this.batchSize=0;this.unloadHandlerCalled=!1;this.highPriorityFlushInterval=1E3;this.lowPriorityFlushInterval=1E4;this.transportationClient=function(b){var e=function(){};b=function(){var b=function(){if(a.XDomainRequest){var d=new a.XDomainRequest;d.onerror=e;d.ontimeout=e;d.onprogress=e;d.onload=e;d.timeout=0;return d}if(a.XMLHttpRequest){d=
new a.XMLHttpRequest;if(!("withCredentials"in d))throw"";return d}return null};return{send:function(a,c){if(c&&a){var e=b();if(!e)throw"";e.open("POST",a,!0);e.setRequestHeader&&e.setRequestHeader("Content-type","text/plain");e.send(c)}},isSupported:!0}}();var k=function(){return{send:function(b,d){if(b&&d&&!a.navigator.sendBeacon(b,d))throw"";},isSupported:!!a.navigator.sendBeacon&&!(a.cordova&&a.cordova.platformId&&"ios"===a.cordova.platformId)}}();return{ajaxClient:b,beaconClient:k}}(this);this.compressor=
function(a){var b=function(d){if(d)switch("undefined"===typeof d?"undefined":q(d)){case "number":return!(d!==d||Infinity===d)&&d.toString().length>a.dictionaryIndex.length;case "boolean":break;case "string":return d.length>a.dictionaryIndex.length;default:return!0}return!1},e=function(d){a.eventsDictionary[d]||(a.eventsDictionary[d]=a.dictionaryIndex++,a.reverseEventsDictionary[a.eventsDictionary[d]]=d);return a.eventsDictionary[d]},h=function(a){if(b(a)){var c=0;a instanceof Array?c=2:a instanceof
Function?c=null:a instanceof Object&&(c=1);switch(c){case 0:return e(a);case 2:for(var f=[],c=0;c<a.length;c++)f[c]=h(a[c]);return f;case 1:c={};for(f in a)Object.prototype.hasOwnProperty.call(a,f)&&(c[e(f)]=-1===g.indexOf(f)?h(a[f]):a[f]);return c}}return a};return{compressData:h,buildPOSTObject:function(){return a.stringify({cs:{dct:a.reverseEventsDictionary},events:a.eventsQueue})}}}(this)}z(b,[{key:"onBeforeUnload",value:function(){!0!==this.unloadHandlerCalled&&(this.flush(this),this.unloadHandlerCalled=
!0)}},{key:"stringify",value:function(a){try{return JSON.stringify(a)}catch(b){console.warn("Fail to stringify data")}return null}},{key:"resetBatch",value:function(){this.eventsQueue=[];this.eventsDictionary={};this.reverseEventsDictionary={};this.highPriorityTimer=this.lowPriorityTimer=this.batchSize=this.dictionaryIndex=0}},{key:"sendWithClient",value:function(a){if(null==this.endpoint||""==this.endpoint)this.ueCount("SushiClientEndpointMissing");else{if(a.isSupported){var b=this.compressor.buildPOSTObject();
return a.send(this.endpoint,b)}throw"";}}},{key:"sendWithPriority",value:function(){for(var a=arguments.length,b=Array(a),f=0;f<a;f++)b[f]=arguments[f];for(a=0;a<b.length;a++){f=b[a];try{return this.sendWithClient(f)}catch(l){}}return null}},{key:"flush",value:function(a){a.eventsQueue.length&&(a.sendWithPriority(a.transportationClient.beaconClient||{},a.transportationClient.ajaxClient||{}),a.resetBatch())}},{key:"startHighPriorityQueueTimer",value:function(){0===this.highPriorityFlushInterval?this.flush(this):
this.highPriorityTimer||(this.highPriorityTimer=this.window.setTimeout(this.flush,this.highPriorityFlushInterval,this))}},{key:"startLowPriorityQueueTimer",value:function(){this.lowPriorityTimer||(this.lowPriorityTimer=this.window.setTimeout(this.flush,this.lowPriorityFlushInterval,this))}},{key:"generateMessageId",value:function(a,b){return a+"-"+b+"-"+this.eventSequence}},{key:"getCurrentISODate",value:function(){var a=new Date,b=function(a){return 10>a?"0"+a:a};return Date.prototype.toISOString?
a.toISOString():a.getUTCFullYear()+"-"+b(a.getUTCMonth()+1)+"-"+b(a.getUTCDate())+"T"+b(a.getUTCHours())+":"+b(a.getUTCMinutes())+":"+b(a.getUTCSeconds())+"."+String((a.getUTCMilliseconds()/1E3).toFixed(3)).slice(2,5)+"Z"}},{key:"decorateEvent",value:function(a){a.timestamp=this.getCurrentISODate();a.sequence=this.eventSequence;a.messageId=this.generateMessageId(a.request_id,Date.now?Date.now():(new Date).getTime())}},{key:"startTimers",value:function(a){(a||{}).n?this.startHighPriorityQueueTimer():
this.startLowPriorityQueueTimer()}},{key:"encodeEvent",value:function(a,b,f){b=b.length;(499===this.eventsQueue.length||524288<this.batchSize+b)&&this.flush(this);this.batchSize+=b;a={data:this.compressor.compressData(a)};this.eventsQueue.push(a);this.startTimers(f)}},{key:"addEvent",value:function(a,b){this.decorateEvent(a,b);var f=this.stringify(a);return f?(this.encodeEvent(a,f,b),!0):!1}},{key:"isValidAPIParam",value:function(a,b){return a&&-1<a.constructor.toString().indexOf(b)}},{key:"isMaxCallsReached",
value:function(){this.eventSequence++;5E4<this.eventSequence&&this.ueCount("SushiClientMaxCallsReached");return 5E4<this.eventSequence}},{key:"isValidAPICall",value:function(a,b){return!this.isMaxCallsReached()&&this.isValidAPIParam(a,"Object")}},{key:"ueCount",value:function(a,b){"undefined"!==typeof ue&&ue&&ue.count&&ue.count("BrandFollowMetrics:"+a,0===b?0:b||(ue.count("BrandFollowMetrics:"+a)||0)+1)}},{key:"processEvent",value:function(a,b){var f=this.unloadHandlerCalled=!1;this.options=b||{};
this.isValidAPICall(a,this.options)&&(f=this.addEvent(a,this.options));f?this.ueCount("ClientEventsSuccess:"+a.event_type):(console.error("Invalid JS SushiEel API call"),this.ueCount("ClientEventsFailed:"+a.event_type));return f}}]);return b}()});"use strict";n.when("A","brand-follow-sushi-client","brand-follow-constants").register("brand-follow-metrics-client",function(g,b,a){var e=g.$;g=document.domain;g=0===g.indexOf("www.amazon")||0===g.indexOf("smile.amazon");var f=new b(m,a.SUSHI_ENDPOINT[g?
"prod":"gamma"]);return{getAttributeMapFromElement:function(b){var f=e(b).data(a.BFID_DATA_KEY),h=e(b).data(a.REQUEST_ID_DATA_KEY),d=e(b).data(a.PLACEMENT_TYPE_DATA_KEY),c=e(b).data(a.PLACEMENT_SUB_TYPE_DATA_KEY),g=e(b).data(a.PLACEMENT_ID_DATA_KEY),m=e(b).data(a.COMPONENT_TYPE_DATA_KEY),n=e(b).data(a.COMPONENT_ID_DATA_KEY),p=e(b).data(a.ELEMENT_TYPE_DATA_KEY);b=e(b).data(a.ELEMENT_ID_DATA_KEY);return{bfid:f,request_id:h,placement_type:d,placement_sub_type:c,placement_id:g,component_type:m,component_id:n,
element_type:p,element_id:b}},buildFollowButtonClickMetricEvent:function(a,b,e){a=this.getAttributeMapFromElement(a);return{bfid:a.bfid,request_id:a.request_id,placement_type:a.placement_type,placement_sub_type:a.placement_sub_type,placement_id:a.placement_id,component_type:a.component_type,component_id:a.component_id,element_type:a.element_type,element_id:a.element_id,event_type:b,tooltip_status:m.brandFollowTooltipStatus,timestamp:Date.now(),event_source:m.location.href,schema_version:1}},processMetricEvent:function(a,
b){f.processEvent(a,b)}}});"use strict";n.when("A","brand-follow-constants","brand-follow-button-tooltip","brand-follow-data-storage-helper","brand-follow-csm-helper").execute("brand-follow-tooltip-helper",function(g,b,a,e,f){var l=g.$,k;try{localStorage.setItem("brand_follow_localStorage_testing_key","brand_follow_localStorage_testing_key"),localStorage.removeItem("brand_follow_localStorage_testing_key"),k=!0}catch(u){k=!1}g.on("brandFollow:followButton:loaded",function(){var e=b.FOLLOW_CSM_PREFIX+
":tooltip";if(null!==b.PAGE_LOCALE&&b.PAGE_LOCALE!==p&&""!==b.PAGE_LOCALE&&"en"===b.PAGE_LOCALE.slice(0,2)){if(k){var r=localStorage.getItem(b.TOOLTIP_LAST_SEEN_KEY),B=localStorage.getItem(b.TOOLTIP_SEEN_COUNTER),w;if(w=h()){var x;try{x=a.getText()!==localStorage.getItem(b.TOOLTIP_LATEST_TEXT_KEY)}catch(C){x=!1}w=!x}if(w||!h()&&r&&!c(r,B)){m.brandFollowTooltipStatus=b.TOOLTIP_STATUS_NOT_SHOWN;return}}r=l(b.Brand_FOLLOW_BUTTON_WITH_TOOLTIP_SELECTOR);if(r.length)if(g.capabilities.mobile||g.capabilities.tablet||
screen.width<=b.BREAKPOINTS.MOBILE){var v=r.get(0),r=l(v).data(b.BFID_DATA_KEY);!r||d(r)?m.brandFollowTooltipStatus=b.TOOLTIP_STATUS_NOT_SHOWN:(a.show(v),t(),k&&localStorage.setItem(b.TOOLTIP_LATEST_TEXT_KEY,a.getText()),m.brandFollowTooltipStatus=b.TOOLTIP_STATUS_SHOWN,"true"!==m.tooltipSeenOnPage&&(q(),m.tooltipSeenOnPage="true",f.incrementCSMCounter(e+":mobile")),n(v)?y():l(m).scroll(g.throttle(function(){n(v)&&y()},200)))}else l(b.Brand_FOLLOW_BUTTON_CONTAINER_SELECTOR).undelegate(b.Brand_FOLLOW_BUTTON_WITH_TOOLTIP_SELECTOR,
"mouseenter mouseleave"),l(b.Brand_FOLLOW_BUTTON_CONTAINER_SELECTOR).delegate(b.Brand_FOLLOW_BUTTON_WITH_TOOLTIP_SELECTOR,"mouseenter mouseleave",function(c){if("mouseenter"===c.type){var h=l(c.target).data(b.BFID_DATA_KEY);!h||d(h)?m.brandFollowTooltipStatus=b.TOOLTIP_STATUS_NOT_SHOWN:(a.show(c.target),t(),k&&localStorage.setItem(b.TOOLTIP_LATEST_TEXT_KEY,a.getText()),m.brandFollowTooltipStatus=b.TOOLTIP_STATUS_SHOWN,"true"!==m.tooltipSeenOnPage&&(q(),m.tooltipSeenOnPage="true",f.incrementCSMCounter(e+
":desktop")))}else"mouseleave"===c.type&&a.hide()});else m.brandFollowTooltipStatus=b.TOOLTIP_STATUS_DISABLED}});var h=function(){try{return"true"===localStorage.getItem(b.FOLLOWED_BRAND_TOOLTIP_SIGNAL)}catch(a){return!1}},d=function(a){try{return b.BRAND_FOLLOW_STATUS.FOLLOWING===e.getFollowStatus(a)}catch(c){return!1}},c=function(a,b){try{return Date.now()-parseInt(a)>6048E5*Math.pow(2,parseInt(b))}catch(c){return!1}},t=function(){k&&localStorage.setItem(b.TOOLTIP_LAST_SEEN_KEY,Date.now().toString())},
n=function(a){a=a.getBoundingClientRect();return 0<=a.top&&0<=a.left&&a.bottom<=(m.innerHeight||document.documentElement.clientHeight)&&a.right<=(m.innerWidth||document.documentElement.clientWidth)},y=function(){setTimeout(function(){a.hide()},b.TOOLTIP_DISPLAY_TIME)},q=function(){if(k){var a=localStorage.getItem(b.TOOLTIP_SEEN_COUNTER);a?(a=parseInt(a)+1,localStorage.setItem(b.TOOLTIP_SEEN_COUNTER,a.toString())):localStorage.setItem(b.TOOLTIP_SEEN_COUNTER,(1).toString())}}});"use strict";n.when("A",
"brand-follow-data-storage-helper","brand-follow-constants","brand-follow-csm-helper").register("brand-follow-shared-utils",function(g,b,a,e){var f=g.$;m.BrandFollowSharedUtils={getLastClickAction:function(g){var k=a.FOLLOW_CSM_PREFIX+":sharedUtils:getLastClickAction";e.incrementCSMCounter(k);var h;h=a.FOLLOW_CSM_PREFIX+":sharedUtils:getBFID";e.incrementCSMCounter(h);g?"string"===typeof g?h=g:g instanceof Element&&1===g.nodeType?((g=f(g).find(a.Brand_FOLLOW_BUTTON_SELECTOR).andSelf().filter(a.Brand_FOLLOW_BUTTON_SELECTOR).first().data(a.BFID_DATA_KEY))||
e.incrementCSMCounter(h+":notFound"),h=g):(e.incrementCSMCounter(h+":unknownInput"),h=void 0):h=void 0;h||e.incrementCSMCounter(k+":emptyBFID");(h=b.getLastClickEvent(h))||e.incrementCSMCounter(k+":emptyResponse");return h},isFollowing:function(e){return b.getFollowStatus(e)===a.BRAND_FOLLOW_STATUS.FOLLOWING}}});"use strict";n.when("A","brand-follow-data-storage-helper","brand-follow-constants").register("on-brand-follow-status-change",function(g,b,a){var e=g.$;g.state.bind("brand-follow-status",
function(f,g){for(var k in g)g.hasOwnProperty(k)&&g[k]&&(b.getFollowStatus(k)===a.BRAND_FOLLOW_STATUS.FOLLOWING?e("[data-bfid\x3d'"+k+"']").each(function(){e(this).text(e(this).data(a.FOLLOWING_TEXT_DATA_KEY));e(this).attr(a.ARIA_LABEL_KEY,e(this).data(a.ARIA_LABEL_FOLLOWING_DATA_KEY))}):e("[data-bfid\x3d'"+k+"']").each(function(){e(this).text(e(this).data(a.FOLLOW_TEXT_DATA_KEY));e(this).attr(a.ARIA_LABEL_KEY,e(this).data(a.ARIA_LABEL_FOLLOW_DATA_KEY))}))})});"use strict";n.when("A").register("brand-follow-button-event-helper",
function(g){return{triggerFollowButtonLoadedEvent:function(){g.trigger("brandFollow:followButton:loaded")},triggerFollowButtonRedirectionEvent:function(b){g.trigger("brandFollow:followButton:redirectToAuthPortal",b)}}});"use strict";n.when("A","brand-follow-data-storage-helper","brand-follow-constants","brand-follow-afs-helper","brand-follow-auth-portal-link-builder","brand-follow-button-event-helper","brand-follow-metrics-client","brand-follow-csm-helper").register("brand-follow-button-click-handler",
function(g,b,a,e,f,l,k,h){var d=g.$;g.on("brandFollow:followButton:loaded",function(){d(a.Brand_FOLLOW_BUTTON_CONTAINER_SELECTOR).undelegate(a.Brand_FOLLOW_BUTTON_WRAPPER_SELECTOR,"click");d(a.Brand_FOLLOW_BUTTON_CONTAINER_SELECTOR).delegate(a.Brand_FOLLOW_BUTTON_WRAPPER_SELECTOR,"click",function(c){var g=a.FOLLOW_CSM_PREFIX+":clickHandler";h.incrementCSMCounter(g);var n=d(this).find(a.Brand_FOLLOW_BUTTON_SELECTOR).first(),p=n.data(a.BFID_DATA_KEY),q=n.data(a.REF_DATA_KEY)||a.FOLLOW_REF_TAG;if(p){var u=
b.getFollowStatus(p);u||(u=n.data(a.FOLLOW_STATUS_DATA_KEY)?a.BRAND_FOLLOW_STATUS.FOLLOWING:a.BRAND_FOLLOW_STATUS.NOT_FOLLOWING);switch(u){case a.BRAND_FOLLOW_STATUS.FOLLOWING:h.incrementCSMCounter(g+":status:following");b.setFollowStatus(p,a.BRAND_FOLLOW_STATUS.PENDING);b.setLastClickEvent(p,a.EVENT_TYPE.UNFOLLOW);e.unfollow(p,q,function(){b.setFollowStatus(p,a.BRAND_FOLLOW_STATUS.NOT_FOLLOWING);var d=k.buildFollowButtonClickMetricEvent(n,a.EVENT_TYPE.UNFOLLOW,c);k.processMetricEvent(d,{n:1})},function(){b.setFollowStatus(p,
a.BRAND_FOLLOW_STATUS.FOLLOWING)});break;case a.BRAND_FOLLOW_STATUS.NOT_FOLLOWING:h.incrementCSMCounter(g+":status:not_following");b.setFollowStatus(p,a.BRAND_FOLLOW_STATUS.PENDING);b.setLastClickEvent(p,a.EVENT_TYPE.FOLLOW);e.follow(p,q,function(){b.setFollowStatus(p,a.BRAND_FOLLOW_STATUS.FOLLOWING);var d=k.buildFollowButtonClickMetricEvent(n,a.EVENT_TYPE.FOLLOW,c);k.processMetricEvent(d,{n:1});try{localStorage.setItem(a.FOLLOWED_BRAND_TOOLTIP_SIGNAL,"true")}catch(e){}},function(){b.setFollowStatus(p,
a.BRAND_FOLLOW_STATUS.NOT_FOLLOWING)},function(){l.triggerFollowButtonRedirectionEvent(c);var a=f.signin();m.location.assign(a)});break;case a.BRAND_FOLLOW_STATUS.NOT_SIGNED_IN:h.incrementCSMCounter(g+":status:not_signed_in");l.triggerFollowButtonRedirectionEvent(c);g=f.signin();m.location.assign(g);break;case a.BRAND_FOLLOW_STATUS.ERROR:h.incrementCSMCounter(g+":status:error");l.triggerFollowButtonLoadedEvent();break;case a.BRAND_FOLLOW_STATUS.PENDING:return h.incrementCSMCounter(g+":status:pending"),
!1;default:h.incrementCSMCounter(g+":status:unknown")}}else h.incrementCSMCounter(g+":emptyBFID")})})});"use strict";n.when("A","brand-follow-data-storage-helper","brand-follow-constants","brand-follow-afs-helper","brand-follow-button-event-helper","brand-follow-csm-helper","on-brand-follow-status-change","ready").register("brand-follow-button-initializer",function(g,b,a,e,f,l){g.on("brandFollow:followButton:loaded",function(){g.$(a.Brand_FOLLOW_BUTTON_WRAPPER_SELECTOR+" "+a.Brand_FOLLOW_BUTTON_SELECTOR).each(function(){var f=
g.$(this),h=f.data(a.BFID_DATA_KEY),d=f.data(a.REF_DATA_KEY)||a.FOLLOW_REF_TAG;if(h!==p){var c=b.getFollowStatus(h);if(c===p||c===a.BRAND_FOLLOW_STATUS.ERROR){c=f.data(a.FOLLOW_STATUS_DATA_KEY);if(f.data(a.BACK_BUTTON_SUPPORT_ENABLED_DATA_KEY)){var n=m.performance||m.webkitPerformance,n=n&&n.navigation&&2==n.navigation.type;!/bot|crawl|spider/i.test(m.navigator&&m.navigator.userAgent)&&n&&(c="")}if(c!==p&&""!==c)b.setFollowStatus(h,c?a.BRAND_FOLLOW_STATUS.FOLLOWING:a.BRAND_FOLLOW_STATUS.NOT_FOLLOWING);
else{b.setFollowStatus(h,a.BRAND_FOLLOW_STATUS.PENDING);var q=a.FOLLOW_CSM_PREFIX+":FetchFollowStatus";l.incrementCSMCounter(""+q);e.getFollowStatusAndInitCsrf(h,d,function(c){b.setFollowStatus(h,c.isFollowing?a.BRAND_FOLLOW_STATUS.FOLLOWING:a.BRAND_FOLLOW_STATUS.NOT_FOLLOWING);l.incrementCSMCounter(q+":success");f.data(a.FOLLOW_STATUS_DATA_KEY)!==c.isFollowing&&l.incrementCSMCounter(q+":FoundDiff")},function(){l.incrementCSMCounter(q+":error");b.setFollowStatus(h,a.BRAND_FOLLOW_STATUS.ERROR)},function(){l.incrementCSMCounter(q+
":notSignedIn");b.setFollowStatus(h,a.BRAND_FOLLOW_STATUS.NOT_SIGNED_IN)})}}else c===a.BRAND_FOLLOW_STATUS.FOLLOWING?(f.text(f.data(a.FOLLOWING_TEXT_DATA_KEY)),f.attr(a.ARIA_LABEL_KEY,f.data(a.ARIA_LABEL_FOLLOWING_DATA_KEY))):(f.text(f.data(a.FOLLOW_TEXT_DATA_KEY)),f.attr(a.ARIA_LABEL_KEY,f.data(a.ARIA_LABEL_FOLLOW_DATA_KEY)))}})});f.triggerFollowButtonLoadedEvent()});"use strict";n.when("A","brand-follow-constants","brand-follow-button-event-helper","ready").execute("brand-follow-button-mutation-observer",
function(g,b,a){var e=g.$;(function(){var f=m.MutationObserver||m.WebKitMutationObserver||m.MozMutationObserver;f!==p&&(new f(function(f,g){var h;g=!1;for(var d=0;d<f.length;d++){h=f[d];if("childList"!==h.type)break;h=h.addedNodes;for(var c,m=0;m<h.length;m++)if(c=h[m],0!==e(c).find(b.Brand_FOLLOW_BUTTON_SELECTOR).length){g=!0;break}if(g){a.triggerFollowButtonLoadedEvent();break}}})).observe(document,{childList:!0,subtree:!0})})()})});
/* ******** */
(function(c){var b=window.AmazonUIPageJS||window.P,d=b._namespace||b.attributeErrors,a=d?d("BrandFollowKataComponentAssets",""):b;a.guardFatal?a.guardFatal(c)(a,window):a.execute(function(){c(a,window)})})(function(c,b,d){});
/* ******** */
